### ISSUE TITLE
Paper?

### ISSUE THREAD

**Issue by grewanhassan** [armaan-rashid/CS224N-final-project#1]
Hi,

First of all, great work!
Have you already published your paper? If so, can you share a link to it? :)

best

**Comment by armaan-rashid** [comment]
Hey Grewan, I just pushed the paper we wrote to the main repo (it's called CS224N Final Report). We had some really interesting results (for some reason, GPT-2 works really well as a query model for detecting text) but didn't have time to explore them super deeply. This project may not be as relevant anymore because we made it in the context of when the OpenAI API didn't let you query GPT 3.5's probabilities, which it might let you do now, I'm not sure! In any case thanks for your interest and be sure to check out Eric Mitchell's [original DetectGPT paper](https://arxiv.org/pdf/2301.11305.pdf) which our paper is based on.
